//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类dict_power。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("dict_power")]
    [Serializable]
    public partial class dict_power : Entity
    {
        #region Model
		private int _id;
		private int? _role_id;
		private string _powername;
		private string _powercode;
		private DateTime? _uptime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 角色ID
		/// </summary>
		[Field("role_id")]
		public int? role_id
		{
			get{ return _role_id; }
			set
			{
				this.OnPropertyValueChange("role_id");
				this._role_id = value;
			}
		}
		/// <summary>
		/// 权限
		/// </summary>
		[Field("powername")]
		public string powername
		{
			get{ return _powername; }
			set
			{
				this.OnPropertyValueChange("powername");
				this._powername = value;
			}
		}
		/// <summary>
		/// 权限代码
		/// </summary>
		[Field("powercode")]
		public string powercode
		{
			get{ return _powercode; }
			set
			{
				this.OnPropertyValueChange("powercode");
				this._powercode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.role_id,
				_.powername,
				_.powercode,
				_.uptime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._role_id,
				this._powername,
				this._powercode,
				this._uptime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "dict_power");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "dict_power", "");
            /// <summary>
			/// 角色ID
			/// </summary>
			public readonly static Field role_id = new Field("role_id", "dict_power", "角色ID");
            /// <summary>
			/// 权限
			/// </summary>
			public readonly static Field powername = new Field("powername", "dict_power", "权限");
            /// <summary>
			/// 权限代码
			/// </summary>
			public readonly static Field powercode = new Field("powercode", "dict_power", "权限代码");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "dict_power", "");
        }
        #endregion
	}
}