//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类dict_menu。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("dict_menu")]
    [Serializable]
    public partial class dict_menu : Entity
    {
        #region Model
		private int _id;
		private string _menuname;
		private int? _pid;
		private string _url;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("menuname")]
		public string menuname
		{
			get{ return _menuname; }
			set
			{
				this.OnPropertyValueChange("menuname");
				this._menuname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pid")]
		public int? pid
		{
			get{ return _pid; }
			set
			{
				this.OnPropertyValueChange("pid");
				this._pid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("url")]
		public string url
		{
			get{ return _url; }
			set
			{
				this.OnPropertyValueChange("url");
				this._url = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.menuname,
				_.pid,
				_.url,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._menuname,
				this._pid,
				this._url,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "dict_menu");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "dict_menu", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field menuname = new Field("menuname", "dict_menu", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field pid = new Field("pid", "dict_menu", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field url = new Field("url", "dict_menu", "");
        }
        #endregion
	}
}