//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_account。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_account")]
    [Serializable]
    public partial class tb_account : Entity
    {
        #region Model
		private int _id;
		private string _projectid;
		private string _deviceid;
		private string _phone;
		private string _email;
		private string _vip;
		private string _licence;
		private DateTime? _uptime;
		private DateTime? _regtime;
		private DateTime? _lasttime;
		private string _ispay;
		private DateTime? _licStartDate;
		private DateTime? _licEndDate;
		private string _smscode;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("projectid")]
		public string projectid
		{
			get{ return _projectid; }
			set
			{
				this.OnPropertyValueChange("projectid");
				this._projectid = value;
			}
		}
		/// <summary>
		/// 设备ID
		/// </summary>
		[Field("deviceid")]
		public string deviceid
		{
			get{ return _deviceid; }
			set
			{
				this.OnPropertyValueChange("deviceid");
				this._deviceid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("phone")]
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange("phone");
				this._phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("email")]
		public string email
		{
			get{ return _email; }
			set
			{
				this.OnPropertyValueChange("email");
				this._email = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("vip")]
		public string vip
		{
			get{ return _vip; }
			set
			{
				this.OnPropertyValueChange("vip");
				this._vip = value;
			}
		}
		/// <summary>
		/// 许可证号
		/// </summary>
		[Field("licence")]
		public string licence
		{
			get{ return _licence; }
			set
			{
				this.OnPropertyValueChange("licence");
				this._licence = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("regtime")]
		public DateTime? regtime
		{
			get{ return _regtime; }
			set
			{
				this.OnPropertyValueChange("regtime");
				this._regtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("lasttime")]
		public DateTime? lasttime
		{
			get{ return _lasttime; }
			set
			{
				this.OnPropertyValueChange("lasttime");
				this._lasttime = value;
			}
		}
		/// <summary>
		/// 是否付费
		/// </summary>
		[Field("ispay")]
		public string ispay
		{
			get{ return _ispay; }
			set
			{
				this.OnPropertyValueChange("ispay");
				this._ispay = value;
			}
		}
		/// <summary>
		/// 许可开始日期
		/// </summary>
		[Field("licStartDate")]
		public DateTime? licStartDate
		{
			get{ return _licStartDate; }
			set
			{
				this.OnPropertyValueChange("licStartDate");
				this._licStartDate = value;
			}
		}
		/// <summary>
		/// 许可结束日期
		/// </summary>
		[Field("licEndDate")]
		public DateTime? licEndDate
		{
			get{ return _licEndDate; }
			set
			{
				this.OnPropertyValueChange("licEndDate");
				this._licEndDate = value;
			}
		}
		/// <summary>
		/// 短信验证码
		/// </summary>
		[Field("smscode")]
		public string smscode
		{
			get{ return _smscode; }
			set
			{
				this.OnPropertyValueChange("smscode");
				this._smscode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.projectid,
				_.deviceid,
				_.phone,
				_.email,
				_.vip,
				_.licence,
				_.uptime,
				_.regtime,
				_.lasttime,
				_.ispay,
				_.licStartDate,
				_.licEndDate,
				_.smscode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._projectid,
				this._deviceid,
				this._phone,
				this._email,
				this._vip,
				this._licence,
				this._uptime,
				this._regtime,
				this._lasttime,
				this._ispay,
				this._licStartDate,
				this._licEndDate,
				this._smscode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_account");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field projectid = new Field("projectid", "tb_account", "");
            /// <summary>
			/// 设备ID
			/// </summary>
			public readonly static Field deviceid = new Field("deviceid", "tb_account", "设备ID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone", "tb_account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field email = new Field("email", "tb_account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field vip = new Field("vip", "tb_account", "");
            /// <summary>
			/// 许可证号
			/// </summary>
			public readonly static Field licence = new Field("licence", "tb_account", "许可证号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field regtime = new Field("regtime", "tb_account", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field lasttime = new Field("lasttime", "tb_account", "");
            /// <summary>
			/// 是否付费
			/// </summary>
			public readonly static Field ispay = new Field("ispay", "tb_account", "是否付费");
            /// <summary>
			/// 许可开始日期
			/// </summary>
			public readonly static Field licStartDate = new Field("licStartDate", "tb_account", "许可开始日期");
            /// <summary>
			/// 许可结束日期
			/// </summary>
			public readonly static Field licEndDate = new Field("licEndDate", "tb_account", "许可结束日期");
            /// <summary>
			/// 短信验证码
			/// </summary>
			public readonly static Field smscode = new Field("smscode", "tb_account", "短信验证码");
        }
        #endregion
	}
}