//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_detail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_detail")]
    [Serializable]
    public partial class tb_detail : Entity
    {
        #region Model
		private int _id;
		private string _phone;
		private string _orderid;
		private DateTime? _createtime;
		private decimal? _money;
		private DateTime? _overtime;
		private DateTime? _uptime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("phone")]
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange("phone");
				this._phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("orderid")]
		public string orderid
		{
			get{ return _orderid; }
			set
			{
				this.OnPropertyValueChange("orderid");
				this._orderid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("createtime")]
		public DateTime? createtime
		{
			get{ return _createtime; }
			set
			{
				this.OnPropertyValueChange("createtime");
				this._createtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("money")]
		public decimal? money
		{
			get{ return _money; }
			set
			{
				this.OnPropertyValueChange("money");
				this._money = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("overtime")]
		public DateTime? overtime
		{
			get{ return _overtime; }
			set
			{
				this.OnPropertyValueChange("overtime");
				this._overtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.phone,
				_.orderid,
				_.createtime,
				_.money,
				_.overtime,
				_.uptime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._phone,
				this._orderid,
				this._createtime,
				this._money,
				this._overtime,
				this._uptime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_detail");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field orderid = new Field("orderid", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field createtime = new Field("createtime", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field money = new Field("money", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field overtime = new Field("overtime", "tb_detail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_detail", "");
        }
        #endregion
	}
}