//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_project。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_project")]
    [Serializable]
    public partial class tb_project : Entity
    {
        #region Model
		private int _id;
		private string _projectid;
		private string _projectname;
		private string _remake;
		private string _istate;
		private string _sms_id;
		private DateTime? _uptime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("projectid")]
		public string projectid
		{
			get{ return _projectid; }
			set
			{
				this.OnPropertyValueChange("projectid");
				this._projectid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("projectname")]
		public string projectname
		{
			get{ return _projectname; }
			set
			{
				this.OnPropertyValueChange("projectname");
				this._projectname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remake")]
		public string remake
		{
			get{ return _remake; }
			set
			{
				this.OnPropertyValueChange("remake");
				this._remake = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("istate")]
		public string istate
		{
			get{ return _istate; }
			set
			{
				this.OnPropertyValueChange("istate");
				this._istate = value;
			}
		}
		/// <summary>
		/// 短信模板ID
		/// </summary>
		[Field("sms_id")]
		public string sms_id
		{
			get{ return _sms_id; }
			set
			{
				this.OnPropertyValueChange("sms_id");
				this._sms_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.projectid,
				_.projectname,
				_.remake,
				_.istate,
				_.sms_id,
				_.uptime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._projectid,
				this._projectname,
				this._remake,
				this._istate,
				this._sms_id,
				this._uptime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_project");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_project", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field projectid = new Field("projectid", "tb_project", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field projectname = new Field("projectname", "tb_project", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field remake = new Field("remake", "tb_project", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field istate = new Field("istate", "tb_project", "");
            /// <summary>
			/// 短信模板ID
			/// </summary>
			public readonly static Field sms_id = new Field("sms_id", "tb_project", "短信模板ID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_project", "");
        }
        #endregion
	}
}