//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_sms_template。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_sms_template")]
    [Serializable]
    public partial class tb_sms_template : Entity
    {
        #region Model
		private int _id;
		private string _smsid;
		private string _content;
		private DateTime? _uptime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("smsid")]
		public string smsid
		{
			get{ return _smsid; }
			set
			{
				this.OnPropertyValueChange("smsid");
				this._smsid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("content")]
		public string content
		{
			get{ return _content; }
			set
			{
				this.OnPropertyValueChange("content");
				this._content = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.smsid,
				_.content,
				_.uptime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._smsid,
				this._content,
				this._uptime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_sms_template");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_sms_template", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field smsid = new Field("smsid", "tb_sms_template", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field content = new Field("content", "tb_sms_template", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_sms_template", "");
        }
        #endregion
	}
}