//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_users。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_users")]
    [Serializable]
    public partial class tb_users : Entity
    {
        #region Model
		private int _id;
		private int? _roleid;
		private string _username;
		private string _pwd;
		private string _realname;
		private DateTime? _uptime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("roleid")]
		public int? roleid
		{
			get{ return _roleid; }
			set
			{
				this.OnPropertyValueChange("roleid");
				this._roleid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("username")]
		public string username
		{
			get{ return _username; }
			set
			{
				this.OnPropertyValueChange("username");
				this._username = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pwd")]
		public string pwd
		{
			get{ return _pwd; }
			set
			{
				this.OnPropertyValueChange("pwd");
				this._pwd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("realname")]
		public string realname
		{
			get{ return _realname; }
			set
			{
				this.OnPropertyValueChange("realname");
				this._realname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.roleid,
				_.username,
				_.pwd,
				_.realname,
				_.uptime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._roleid,
				this._username,
				this._pwd,
				this._realname,
				this._uptime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_users");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field roleid = new Field("roleid", "tb_users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field username = new Field("username", "tb_users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field pwd = new Field("pwd", "tb_users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field realname = new Field("realname", "tb_users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_users", "");
        }
        #endregion
	}
}