//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_version。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_version")]
    [Serializable]
    public partial class tb_version : Entity
    {
        #region Model
		private int _id;
		private string _apptitle;
		private string _appname;
		private string _url;
		private string _msg;
		private string _text;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("apptitle")]
		public string apptitle
		{
			get{ return _apptitle; }
			set
			{
				this.OnPropertyValueChange("apptitle");
				this._apptitle = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("appname")]
		public string appname
		{
			get{ return _appname; }
			set
			{
				this.OnPropertyValueChange("appname");
				this._appname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("url")]
		public string url
		{
			get{ return _url; }
			set
			{
				this.OnPropertyValueChange("url");
				this._url = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("msg")]
		public string msg
		{
			get{ return _msg; }
			set
			{
				this.OnPropertyValueChange("msg");
				this._msg = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("text")]
		public string text
		{
			get{ return _text; }
			set
			{
				this.OnPropertyValueChange("text");
				this._text = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.apptitle,
				_.appname,
				_.url,
				_.msg,
				_.text,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._apptitle,
				this._appname,
				this._url,
				this._msg,
				this._text,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_version");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_version", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field apptitle = new Field("apptitle", "tb_version", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field appname = new Field("appname", "tb_version", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field url = new Field("url", "tb_version", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field msg = new Field("msg", "tb_version", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field text = new Field("text", "tb_version", "");
        }
        #endregion
	}
}