//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类tb_vip。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("tb_vip")]
    [Serializable]
    public partial class tb_vip : Entity
    {
        #region Model
		private int _id;
		private int? _projectid;
		private string _goodsname;
		private string _vip;
		private decimal? _money;
		private string _level;
		private DateTime? _uptime;
		private int? _days;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("projectid")]
		public int? projectid
		{
			get{ return _projectid; }
			set
			{
				this.OnPropertyValueChange("projectid");
				this._projectid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("goodsname")]
		public string goodsname
		{
			get{ return _goodsname; }
			set
			{
				this.OnPropertyValueChange("goodsname");
				this._goodsname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("vip")]
		public string vip
		{
			get{ return _vip; }
			set
			{
				this.OnPropertyValueChange("vip");
				this._vip = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("money")]
		public decimal? money
		{
			get{ return _money; }
			set
			{
				this.OnPropertyValueChange("money");
				this._money = value;
			}
		}
		/// <summary>
		/// vip等级
		/// </summary>
		[Field("level")]
		public string level
		{
			get{ return _level; }
			set
			{
				this.OnPropertyValueChange("level");
				this._level = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uptime")]
		public DateTime? uptime
		{
			get{ return _uptime; }
			set
			{
				this.OnPropertyValueChange("uptime");
				this._uptime = value;
			}
		}
		/// <summary>
		/// 使用天数
		/// </summary>
		[Field("days")]
		public int? days
		{
			get{ return _days; }
			set
			{
				this.OnPropertyValueChange("days");
				this._days = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.projectid,
				_.goodsname,
				_.vip,
				_.money,
				_.level,
				_.uptime,
				_.days,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._projectid,
				this._goodsname,
				this._vip,
				this._money,
				this._level,
				this._uptime,
				this._days,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "tb_vip");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "tb_vip", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field projectid = new Field("projectid", "tb_vip", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field goodsname = new Field("goodsname", "tb_vip", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field vip = new Field("vip", "tb_vip", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field money = new Field("money", "tb_vip", "");
            /// <summary>
			/// vip等级
			/// </summary>
			public readonly static Field level = new Field("level", "tb_vip", "vip等级");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uptime = new Field("uptime", "tb_vip", "");
            /// <summary>
			/// 使用天数
			/// </summary>
			public readonly static Field days = new Field("days", "tb_vip", "使用天数");
        }
        #endregion
	}
}